---
- name: Using Jinja in Playbook
  hosts: planetexpress
  connection: ssh
  gather_facts: true    # required for ansible_facts

  tasks:


   - name: Display all ansible_facts
     debug:
       var: ansible_facts
       verbosity: 2     # will only run if you included -vv to the command line


   - name: What ansible_facts.os_family contain
     debug:
       var: ansible_facts.os_family


   - name: What ansible_facts.lsb contain
     debug:
       var: ansible_facts.lsb

   - name: Runs only on hosts that match conditional
     debug:
       msg: "I am a Debian host running at least ver 18 of my OS"
     when: ansible_facts.os_family == "Debian" and ansible_facts.lsb.major_release | int >= 18
