- name: mars weather
  hosts: localhost
  connection: local
  
  tasks:
  - name: Pull Mars weather
    nasa_mars_weather:
      name: 2021-04-27-marsweather   # the module adds *.txt to the file name
      apikey: cSenR2vzhHmD4blGDx8dRnPOXJASACEavOWAAMBY
